//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public int KullanıcıID { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Şifre { get; set; }
        public string Rol { get; set; }
        public Nullable<System.DateTime> OluşturulmaTarihi { get; set; }
    }
}
